language: ruby
rvm:
- 2.0.0-p247
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: kqH1nwKuOzRfv+iJMDLmhQ8wwp5b+RvgeTv/1hyBtB9CSGKXCDUgS0xVPhaZDYKex2LwPjlNC3Ljb9iDf7CD2SBqVdW1wCvnAluurZtLiDVirjmvM3a+hPfo8FbnvTMBPyYxzTa9BUDi69FLty2jxbRx9sHCsxBjD5hXylcth1k=
  app:
    develop: websiteone-develop
    master: websiteone-master