language: ruby
rvm:
- 2.0.0-p247
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: CzwqozXqTBrn74UZJB+hFdFlS3cOqsLZzCQ5MQKI4ejNWG9Hhia08euPH3iqFea43foCuIgczdTkx4gBg34prdEpaZkaWmwMJ0cwFjrI6B04QfPETV8iMGJO6eLKpQbOJz+Sa7jaMiTpWGoIVfDsy1uXbwAk5/XZfJoCik/aLn4=
  app:
    develop: websiteone-develop
    master: websiteone-master