language: ruby
rvm:
- 2.0.0-p247
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: kzWKAeVxm2ZRP+51KM0t8JIKDAPmpoVG9tuZ6sRuW882Ns/zwgHjfObRtJmgNeiHDFS40y/GnT1MGxikFBGD/AYZdQkGfwEiGgUDFYxKFOv9itpc+dri9eEVf0qEh2SI2CnV8Zt3f/bIrvo8XEPxUW3hl3nSsYjhab/h/EAkLIA=
  app:
    develop: websiteone-develop
    master: websiteone-master