language: ruby
rvm:
  - 2.0.0-p247
  #- 2.1.0
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake cucumber
- bundle exec rake spec

deploy:
  provider: heroku
  api_key: 4339362a-3bcb-4cce-8004-a2584c4bc1cc
  app:
    develop: websiteone-develop

