development: &dev
  adapter: postgresql
  encoding: unicode
  database: websiteone_development
  pool: 5
  username: 
  password:

test: &test
  <<: *dev
  database: websiteone_test

production:
  <<: *dev
  database: websiteone_production

cucumber:
  <<: *test